controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hexapod_joint_controller:
      type: position_controllers/JointGroupPositionController

hexapod_joint_controller:
  ros__parameters:
    joints:
      - rf_coxa_joint
      - rf_femur_joint
      - rf_tibia_joint
      - rm_coxa_joint
      - rm_femur_joint
      - rm_tibia_joint
      - rb_coxa_joint
      - rb_femur_joint
      - rb_tibia_joint
      - lf_coxa_joint
      - lf_femur_joint
      - lf_tibia_joint
      - lm_coxa_joint
      - lm_femur_joint
      - lm_tibia_joint
      - lb_coxa_joint
      - lb_femur_joint
      - lb_tibia_joint
    interface_name: position
